const express = require('express');
const router = express.Router();
const  jobController =require('../controller/jobController');
router.post('/create',jobController.create);
router.get('/find',jobController.getAll);
router.put('/update',jobController.update);
router.post('/remove', jobController.deleteById);
router.post('/findspecified',jobController.getSpecified);
router.post('/findposted',jobController.findposted);
router.post('/addapplied',jobController.appliedids);
module.exports=router;